### ISSUE TITLE
class tag appends file name to the front of class name in index

### ISSUE THREAD

**Issue by FatalistError** [jtackaberry/luadox#11]
`@class` tag appends the file to the front of the name in the index. So where my classes each have their own file, it does this:

![image](https://github.com/jtackaberry/luadox/assets/58855799/3ced6094-cc13-4f85-81e5-d9e90a8c7e98)

how do I fix this? it's very frustrating and very stupid.

**Comment by jtackaberry** [comment]
Please use someone else's Lua documentation generator. I don't want to spend my limited free time dealing with your attitude.

**Comment by FatalistError** [comment]
> Please use someone else's Lua documentation generator. I don't want to spend my limited free time dealing with your attitude.

lol that's actually too funny. "attitude", what attitude. Seems really unnecessary to close an issue like this, I mean I scoured the documentation on this, and I spent hours documenting my code with this, and now it doesn't work and you're telling me "I don't wanna fix it, use another doc gen". So basically instead of even acknowledging a problem, you're telling me to rewrite like 100s of lines of docs? Cool man, hope you have a great day.

**Comment by FatalistError** [comment]
oh, and by the way, i discovered recently that this issue actually entirely breaks the site. It makes links show up as 404 if you name the class with starting with a capital letter, and then if you don't it somehow breaks the fields (I assume as a result of some weird reference problems). But yes, you're welcome to keep a poorly maintained and buggy doc gen because you don't like the tone of somebody who's frustrated about _unexpected behavior_ (ironic) in your library. Honestly I thought that this would do better with classes that's the whole reason I used it instead of Ldoc, but currently I cannot find any advantages especially with the complete lack of maintenance.

And hell, I would have been willing to contribute even.

**Comment by jtackaberry** [comment]
I'm actually interested in fixing bugs, but not if it means I have to deal with angry users to do it.  You're coming into an open source project with a hostility and sense of entitlement I don't feel is worth the frustration in exchange for the zero dollars I get paid for it.  That you can't sense that you're projecting your hostility onto me is only contributing to the core problem.

**Comment by FatalistError** [comment]
why is your immediate assumption that it's going to be a hostile conversation just because I expressed frustration with the problem I was experiencing. I had no intent to attack you.

**Comment by jtackaberry** [comment]
Because up to that point, given #10 and #11, 100% of the interactions I'd had with you were abrasive.  I get being frustrated when something isn't working right, I really do, but it's simply not productive to say some behavior you don't understand is "stupid" (even if it's unintended behavior) or some documentation language is "unhelpful" because it comes across as resentful.

**Comment by FatalistError** [comment]
> Because up to that point, given #10 and #11, 100% of the interactions I'd had with you were abrasive. I get being frustrated when something isn't working right, I really do, but it's simply not productive to say some behavior you don't understand is "stupid" (even if it's unintended behavior) or some documentation language is "unhelpful" because it comes across as resentful.

well, fair enough. I'll try and be better in the future. Though I think it's worth mentioning that calling specific documentation "unhelpful" is kind of the only way you can describe it in that case. "unhelpful" = "It does not help" = "It does not mean anything to me". I literally have no idea what that documentation is trying to say, that's not to mean resentment, it's just not clear to me.

**Comment by FatalistError** [comment]
I think what's happening is it's trying to link the name of the file which is currently not the name of the class. But when it's the same as the name of the class it creates... bigger problems.

**Comment by FatalistError** [comment]
![image](https://github.com/user-attachments/assets/69fe4cfd-c72f-484c-86ab-ee2ff3980bea)
such-as it becoming a module. So it's trying to make this file a module no matter what, and it's not rendering it because it's empty. So instead making a link to the class its making a link to the module, but if the module is the same as the class name it isn't empty? I'm not sure how the internal workings go, so I wouldn't know if that's accurate

**Comment by rdw-software** [comment]
@FatalistError

> it's very frustrating and very stupid

This first part is understandable but certainly *unhelpful* (in the truest sense of the word). And the second part... well.
 
Your posts could be reworded to express less emotion and include more actionable feedback, as well as provide more technical details. This would almost certainly increase your chances of receiving the help you were seeking, prompt the author to improve the documentation, and leave everyone (including other users of the tool) better off instead of resulting in an unproductive and unpleasant exchange between two strangers that ultimately could've been avoided.

Since I'm already here (and I'm quite familiar with the frustration that you expressed)... here's some suggestions:

> class tag appends the file to the front of the name in the index. So where my classes each have their own file, it does this:
> how do I fix this?

This would likely have been received well if it wasn't for the outburst of emotion afterwards. But still, you could explicitly state what you were expecting to see, what steps you've attempted to resolve or even just narrow down the problem, and if the documentation was confusing to you, mention which parts exactly weren't helpful and what would've made them more useful to you when looking to fix the problem that prompted you to open this issue.

> **lol that's actually too funny. "attitude", what attitude. Seems really unnecessary to close an issue like this**, I mean I scoured the documentation on this, and I spent hours documenting my code with this, **and now it doesn't work and you're telling me "I don't wanna fix it, use another doc gen". So basically instead of even acknowledging a problem, you're telling me to rewrite like 100s of lines of docs? Cool man, hope you have a great day.**

The bold parts aren't adding anything. It's fine to state that you spent a significant amount of time and would have preferred to not have to encounter this problem (although it's somewhat redundant - no one wants that).

> **oh, and by the way,** i discovered recently that this issue actually entirely breaks the site. It makes links show up as 404 if you name the class with starting with a capital letter, and then if you don't it somehow breaks the fields (I assume as a result of **some weird reference problems). But yes, you're welcome to keep a poorly maintained and buggy doc gen because you don't like the tone of somebody who's frustrated about unexpected behavior (ironic) in your library**. Honestly I thought that this would do better with classes that's the whole reason I used it instead of Ldoc, but currently I cannot find any advantages **especially with the complete lack of maintenance.**

Again some parts aren't helping anyone solve the problem. The rest probably should've been in the first post?

> And hell, I would have been willing to contribute even.

That sounds rather passive-aggressive - understandable given your frustration, though ultimately uncalled for. Offering to  contribute to an Open Source project is a great idea, but this isn't how you do it. You seem to assume that it's self-evident your contributions would be valuable (not saying they aren't, BTW!). It's usually up to potential contributors to "prove" that this is the case, and that they have the maturity to collaborate with other people in a public space, in a way that produces benefits outweighing the cost - which includes demands on the project maintainer's time and energy.

None of this is intended as a personal attack. I hope you can learn from the experience. Have a nice day!
